services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: voucher-pool-app
    ports:
      - '${PORT}:${PORT}'
    env_file:
      - env/.env.development
      - .env
    volumes:
      - .:/app
    # overwrite the cmd in the Dockerfile
    command: ['bash', '/app/scripts/docker-entrypoint-dev.sh']
    networks:
      - app-network
    depends_on:
      - database

  database:
    image: postgres:17.2
    container_name: voucher-pool-database
    ports:
      - '5435:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: voucher_pool_development
    volumes:
      - voucher-pool-postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  voucher-pool-postgres-data:
networks:
  app-network: {}
